# Site settings
name: Brody Berson
title: Brody Berson | Partner & Integrations Focused Engineer
description: Software Engineer focused on working with partners to help integrate APIs into their own products
url: https://mynamebrody.com/
baseurl: ''
email: brody@hey.com
cover: https://mynamebrody.com/img/og.png
logo: https://mynamebrody.com/img/emojis/technologist.png
resume: https://mynamebrody.com/resume.pdf
social:
  - title: email
    url: mailto:brody@hey.com
  - title: twitter
    url: https://twitter.com/brody_berson
  - title: instagram
    url: https://instagram.com/mynamebrody
  - title: medium
    url: https://medium.com/@mynamebrody
  - title: github
    url: https://github.com/mynamebrody
  - title: linkedin
    url: https://www.linkedin.com/in/brodyharrisberson

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
